apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-wisecow-app # Unique key/name of the Deployment instance that we want to create
spec: # Deployment specifications
  replicas: 2 # Number of Pods that should exist at all times
  selector:
    matchLabels:
      app: kubernetes-deployment-wisecow-app # Label selector for the Pods (This label should be same as the pod label name)
  template:
    metadata:
      labels:
        app: kubernetes-deployment-wisecow-app
    spec:
      containers:
        - name: kubernetes-deployment-wisecow-app
          image: baisyaanirban/wisecow-app:latest
          ports:
            - containerPort: 4499

---
apiVersion: v1
kind: Service
metadata:
  name: service-wisecow-app   # Unique key of the Service instance

spec:
  selector:
    app: kubernetes-deployment-wisecow-app # When we create a service it checks the label of the running pod and if the label matches then the service will be created and the pod will be exposed to the outside world
  ports:
    # Accept traffic sent to port 8080
    - protocol: TCP
      port: 8080
      targetPort: 4499